settings:
  log_level: INFO
  update_interval: 500
  market_pairs:
    - ETH/USDT
    - BTC/USDT
    - SHIB/USDT
    - DOGE/USDT
    - FET/USDT
    - WIF/USDT
    - SOL/USDT
    - ADA/USDT
    - AVAX/USDT
    - BNB/USDT
    - FLOKI/USDT
    - REI/USDT
    - DAI/USDT
    - RNDR/USDT

exchanges:
  huobipro:
    required:
      enabled: true
  binance:
    required:
      enabled: true

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 50
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 5m
      period_count: 14
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 5m
      period_count: 14
  momentum:
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1d
      period_count: 10
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1h
      period_count: 12
  macd:
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - macd
      hot: 0
      cold: 0
      candle_period: 15m
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - macdsignal
      hot: 0
      cold: 0
      candle_period: 15m
  obv:
    - enabled: false
  mfi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - mfi
      hot: 20
      cold: 80
      candle_period: 5m
      period_count: 14
  ichimoku:
    - enabled: true
  bollinger:
    - enabled: true
      candle_period: 1h
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
  aroon_oscillator:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      sma_vol_period: 50
      period_count: 14
      signal:
        - aroon
      candle_period: 1h
  klinger_oscillator:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      ema_short_period: 34
      ema_long_period: 55
      signal_period: 13
      signal:
        - kvo
        - kvo_signal
      candle_period: 1d
  adx:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - adx
        - pdi
        - ndi
      hot: 50
      cold: 25
      candle_period: 1d
      period_count: 14
  iiv:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - iiv
      hot: 5
      cold: 0
      candle_period: 5m
  sqzmom:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      candle_period: 1d
      signal:
        - close

informants:
  ema:
    - enabled: true
      signal:
        - ema
      candle_period: 1d
      period_count: 10
    - enabled: true
      signal:
        - ema
      candle_period: 1d
      period_count: 30

crossovers:
  std_crossover:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      key_indicator: ema
      key_indicator_index: 0
      key_indicator_type: informants
      key_signal: ema
      crossed_indicator: ema
      crossed_indicator_index: 1
      crossed_indicator_type: informants
      crossed_signal: ema
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      key_indicator: macd
      key_indicator_index: 0
      key_indicator_type: indicators
      key_signal: macd
      crossed_indicator: macd
      crossed_indicator_index: 1
      crossed_indicator_type: indicators
      crossed_signal: macdsignal

notifiers:
  telegram:
    required:
      token: 4318021XXXX
      chat_id: -300XXXXXXX
    optional:
      parse_mode: html
      template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}"